
---
version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - "5432:5432"

    webserver:
        image: airflow_local_dev_1
        restart: always
        depends_on:
            - postgres
        environment:
            - AIRFLOW_HOME_BI=/opt/airflow/
            - LOAD_EX=n
            - EXECUTOR=Local
            - PYTHONPATH=/opt/airflow/python_scripts
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ${AIRFLOW_1_CONTENT_FOLDER}/dags:/opt/airflow/dags
            - ${AIRFLOW_1_CONTENT_FOLDER}/python_scripts:/opt/airflow/python_scripts
            - ${AIRFLOW_1_CONTENT_FOLDER}/sql_scripts:/opt/airflow/sql_scripts
            - ./airflow_1/requirements.txt:/opt/airflow/requirements.txt
            - ~/.config/gcloud/application_default_credentials.json:/opt/airflow/.config/gcloud/application_default_credentials.json
        ports:
            - "8081:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
